### PR TITLE
EMH addition to PR#1 adding code to categorize InstitutionalAffiliation

### PR DESCRIPTION
**Pull request by ehumph**
This adds to Kate's PR #1. I am piggybacking.

Adding code that creates a 9-option categorical variable Institutional.Type using InstitutionalAffiliation. This can be changed to include fewer options.

Created categories for Institutional.Type are "R1 University", "R2 University", "Community College", "Medical Center or School", "International Location", "Research Center", "NIH", "Industry", "Unknown"

### CODE REVIEW

**Comment by ehumph** [comment]
@kweav Do you want me to create the Institutional.Type variable as class character or class factor?

**Comment by kweav** [comment]
PR #7 is pushed to reduce the number of institution names/synchronize them like we discussed in the meeting earlier. Thanks!

**Comment by kweav** [comment]
> @kweav Do you want me to create the Institutional.Type variable as class character or class factor?

Great question -- I think it's fine as character class. A factor class could be nice if we wanted to set a specific order, but I can't think of a specific case/order that we want right now

**Comment by kweav** [comment]
Having incorporated this information in PR #7, closing this one.

**Pull request closed without merging**
